# Generated by Django 4.0.5 on 2022-07-17 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('base', '0001_initial'), ('base', '0002_tour_category_tour_website_alter_tour_contact'), ('base', '0003_hotel_restaurants_reviews'), ('base', '0004_dummylatlng'), ('base', '0005_remove_dummylatlng_lat_remove_dummylatlng_lng_and_more'), ('base', '0006_alter_dummylatlng_latlng'), ('base', '0007_alter_tour_rating'), ('base', '0008_remove_dummylatlng_latlng_dummylatlng_lat_and_more'), ('base', '0009_alter_dummylatlng_lat_alter_dummylatlng_lng'), ('base', '0010_delete_dummylatlng'), ('base', '0011_dummylatlng'), ('base', '0012_alter_dummylatlng_lat_alter_dummylatlng_lng'), ('base', '0013_alter_dummylatlng_lat_alter_dummylatlng_lng'), ('base', '0014_alter_dummylatlng_lat_alter_dummylatlng_lng'), ('base', '0015_dummylatlng_name_alter_dummylatlng_lat_and_more'), ('base', '0016_delete_dummylatlng'), ('base', '0017_dummylatlng'), ('base', '0018_remove_restaurants_website'), ('base', '0019_rename_restaurants_restaurant'), ('base', '0020_alter_restaurant_rating'), ('base', '0021_repairshop'), ('base', '0022_transport'), ('base', '0023_alter_hotel_rating_alter_repairshop_rating_and_more'), ('base', '0024_registeredbusiness_hotel_createadat_hotel_updateat_and_more'), ('base', '0007_tour_image'), ('base', '0024_merge_20220704_2205'), ('base', '0025_merge_20220705_2134'), ('base', '0026_remove_repairshop_createadat_and_more'), ('base', '0027_alter_registeredbusiness_banner_and_more'), ('base', '0028_tourreviews_delete_reviews'), ('base', '0029_rename_tour_id_tourreviews_tour'), ('base', '0007_users'), ('base', '0008_users_country_users_mail_users_state_alter_users_dob_and_more'), ('base', '0009_alter_users_phone'), ('base', '0010_remove_users_mail_users_email_users_gender'), ('base', '0030_merge_20220709_2315'), ('base', '0031_profile_delete_users'), ('base', '0031_alter_tour_category'), ('base', '0032_merge_20220710_1210'), ('base', '0032_merge_20220710_0643'), ('base', '0033_merge_20220710_1329'), ('base', '0034_remove_profile_dob_remove_profile_country_and_more'), ('base', '0035_alter_profile_id'), ('base', '0036_alter_profile_id'), ('base', '0037_profile_dob'), ('base', '0038_profile_profile_img'), ('base', '0039_remove_profile_profile_img_profile_image_and_more'), ('base', '0040_profile_phone'), ('base', '0041_rename_profile_profile_user'), ('base', '0042_alter_profile_id_alter_profile_user'), ('base', '0043_alter_profile_image'), ('base', '0044_alter_profile_gender_alter_profile_image_and_more'), ('base', '0045_alter_profile_dob'), ('base', '0046_alter_profile_dob'), ('base', '0047_alter_profile_dob'), ('base', '0048_alter_profile_dob'), ('base', '0049_alter_profile_image'), ('base', '0050_alter_profile_image')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_fare', models.FloatField(default=0)),
                ('address', models.CharField(max_length=700)),
                ('contact', models.CharField(max_length=10)),
                ('hours_open', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('category', models.CharField(choices=[('1', 'Adventure'), ('2', 'Trekking'), ('3', 'Hiking')], default='1', max_length=1)),
                ('website', models.CharField(default='www.google.com', max_length=50)),
                ('createadAt', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='images/recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('website', models.CharField(default='www.google.com', max_length=50)),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('createadAt', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('createadAt', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyLatLng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredBusiness',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=700)),
                ('description', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=6)),
                ('category', models.CharField(choices=[('1', 'Restaurant'), ('2', 'Hotel'), ('3', 'Clinic'), ('4', 'Hospital'), ('5', 'Pharmacy'), ('6', 'Repair Shop'), ('7', 'Travel')], default='5', max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=50, null=True)),
                ('rating', models.FloatField(default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('logo', models.ImageField(null=True, upload_to='images/regBiz')),
                ('banner', models.ImageField(null=True, upload_to='images/regBiz')),
                ('createadAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourReviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=500)),
                ('createadAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Dont want to specify')], default='1', max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(blank=True, choices=[('1', 'User'), ('2', 'Business')], default='1', max_length=1)),
                ('DOB', models.DateField(blank=True, default='2001-01-01')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
