# Generated by Django 4.0.5 on 2022-06-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('1', 'Hiking'), ('2', 'Trekking'), ('3', 'Adventure')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='website',
            field=models.CharField(default='www.google.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
