# Generated by Django 4.0.5 on 2022-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dummylatlng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummylatlng',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='dummylatlng',
            name='lng',
        ),
        migrations.AddField(
            model_name='dummylatlng',
            name='latLng',
            field=models.CharField(default='12.959552183345458, 77.48413863329532', max_length=100),
        ),
    ]
