# Generated by Django 4.0.5 on 2022-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_dummylatlng_lat_remove_dummylatlng_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummylatlng',
            name='latLng',
            field=models.CharField(default='', max_length=100),
        ),
    ]
