# Generated by Django 4.0.5 on 2022-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dummylatlng_latlng'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='icons/recommendation'),
        ),
    ]
