# Generated by Django 4.0.5 on 2022-06-25 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dummylatlng_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
