# Generated by Django 4.0.5 on 2022-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_dummylatlng_latlng_dummylatlng_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummylatlng',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dummylatlng',
            name='lng',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
