# Generated by Django 4.0.5 on 2022-06-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_dummylatlng_lat_alter_dummylatlng_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyLatLng',
        ),
    ]
