# Generated by Django 4.0.5 on 2022-06-29 14:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_dummylatlng_lat_alter_dummylatlng_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummylatlng',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dummylatlng',
            name='lng',
            field=models.DecimalField(decimal_places=15, default=Decimal('0'), max_digits=20),
        ),
    ]
