# Generated by Django 4.0.5 on 2022-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_dummylatlng_lat_alter_dummylatlng_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummylatlng',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dummylatlng',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dummylatlng',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
