# Generated by Django 4.0.5 on 2022-06-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_dummylatlng_name_alter_dummylatlng_lat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyLatLng',
        ),
    ]
