# Generated by Django 4.0.5 on 2022-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_dummylatlng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='website',
        ),
    ]
