# Generated by Django 4.0.5 on 2022-07-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_restaurants_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
