# Generated by Django 4.0.5 on 2022-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tour_image'),
        ('base', '0023_alter_hotel_rating_alter_repairshop_rating_and_more'),
    ]

    operations = [
    ]
