# Generated by Django 4.0.5 on 2022-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_merge_20220704_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='subtext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
