# Generated by Django 4.0.5 on 2022-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_merge_20220704_2205'),
        ('base', '0024_registeredbusiness_hotel_createadat_hotel_updateat_and_more'),
    ]

    operations = [
    ]
