# Generated by Django 4.0.5 on 2022-07-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_tour_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='destination',
        ),
    ]
