# Generated by Django 4.0.5 on 2022-07-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_repairshop_createadat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredbusiness',
            name='banner',
            field=models.ImageField(null=True, upload_to='images/regBiz'),
        ),
        migrations.AlterField(
            model_name='registeredbusiness',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/regBiz'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='images/recommendation'),
        ),
    ]
