# Generated by Django 4.0.5 on 2022-07-07 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_registeredbusiness_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourReviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=500)),
                ('createadAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tour')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
