# Generated by Django 4.0.5 on 2022-07-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_tourreviews_delete_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourreviews',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
