# Generated by Django 4.0.5 on 2022-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_tour_destination_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.CharField(choices=[('1', 'Bangalore'), ('2', 'Dakshina Kannada'), ('3', 'Udupi'), ('4', 'Uttara Kannada')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
