# Generated by Django 4.0.5 on 2022-07-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_users_mail_users_email_users_gender'),
        ('base', '0029_rename_tour_id_tourreviews_tour'),
    ]

    operations = [
    ]
