# Generated by Django 4.0.5 on 2022-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_tour_place_alter_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.CharField(choices=[('4', 'Bangalore'), ('5', 'Dakshina Kannada'), ('6', 'Udupi'), ('7', 'Uttara Kannada')], default='4', max_length=1),
        ),
    ]
