# Generated by Django 4.0.5 on 2022-07-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_merge_20220709_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Dont want to specify')], default='1', max_length=1)),
                ('DOB', models.DateField(blank=True, default='2001-01-01')),
                ('phone', models.CharField(max_length=10)),
                ('country', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('profile', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
