# Generated by Django 4.0.5 on 2022-07-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_tour_category'),
        ('base', '0031_profile_delete_users'),
    ]

    operations = [
    ]
