# Generated by Django 4.0.5 on 2022-07-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_merge_20220710_0643'),
        ('base', '0032_merge_20220710_1210'),
    ]

    operations = [
    ]
