# Generated by Django 4.0.5 on 2022-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, default='2001-01-01'),
        ),
    ]
