# Generated by Django 4.0.5 on 2022-07-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
