# Generated by Django 4.0.5 on 2022-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_profile_profile_img_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
