# Generated by Django 4.0.5 on 2022-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
