<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-07-13 12:07
=======
# Generated by Django 4.0.5 on 2022-07-13 12:51
>>>>>>> 6849365cba17677896bee5b988b8c7ae7b043aac

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
=======
            field=models.ImageField(null=True, upload_to='profile_pics'),
>>>>>>> 6849365cba17677896bee5b988b8c7ae7b043aac
        ),
    ]
