# Generated by Django 4.0.5 on 2022-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='instructions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='places_nearby',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hours_open',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
