# Generated by Django 4.0.5 on 2022-07-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_merge_20220710_1157'),
        ('base', '0057_alter_tour_image'),
    ]

    operations = [
    ]
