# Generated by Django 4.0.5 on 2022-07-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_merge_0032_merge_20220710_1157_0057_alter_tour_image'),
        ('base', '0061_business'),
    ]

    operations = [
    ]
