# Generated by Django 4.0.5 on 2022-07-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_merge_20220715_1245'),
        ('base', '0063_delete_dummylatlng_delete_hotel_delete_repairshop_and_more'),
    ]

    operations = [
    ]
