# Generated by Django 4.0.5 on 2022-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_merge_20220717_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='createadAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
