# Generated by Django 4.0.5 on 2022-07-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_merge_20220718_2047'),
        ('base', '0065_alter_tour_createadat'),
    ]

    operations = [
    ]
