# Generated by Django 4.0.5 on 2022-07-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.CharField(choices=[('1', 'Bangalore'), ('2', 'Dakshina Kannada'), ('3', 'Udupi'), ('4', 'Uttara Kannada')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='subtext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
