# Generated by Django 4.0.5 on 2022-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_tour_place_tour_subtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredbusiness',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/regBiz'),
        ),
        migrations.AlterField(
            model_name='registeredbusiness',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/regBiz'),
        ),
        migrations.AlterField(
            model_name='registeredbusiness',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registeredbusiness',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
