# Generated by Django 4.0.5 on 2022-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_registeredbusiness_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredbusiness',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
