# Generated by Django 4.0.5 on 2022-08-08 06:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_tour_end_month_tour_start_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_month',
        ),
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
