# Generated by Django 4.0.5 on 2022-08-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_tour_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
