# Generated by Django 4.0.5 on 2022-08-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_remove_tour_end_month_remove_tour_start_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
