# Generated by Django 4.0.5 on 2022-08-10 04:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_tour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
