# Generated by Django 4.0.5 on 2022-08-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_remove_profile_role'),
        ('base', '0076_alter_tour_date'),
    ]

    operations = [
    ]
