# Generated by Django 4.0.5 on 2022-08-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_mailmessage_subscribers'),
        ('base', '0078_savedtour'),
    ]

    operations = [
    ]
